import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { createGlobalStyle } from 'styled-components'

const GlobalStyle = createGlobalStyle`
  h1{
    color: pink;
  }
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <GlobalStyle/>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/testComponents">
        {/* link 연습하기 ㅋㅋ */}
        <h1>main page test</h1>
      </Link>
    </div>
  )
}
